yaml
name: Build APK (Buildozer 2025)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git ccache libffi-dev libssl-dev \
            libsqlite3-dev libjpeg-dev libpng-dev zlib1g-dev \
            openjdk-11-jdk unzip python3-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36

      - name: Build (debug)
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
