name: Build APK (Buildozer OCR Offline)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git ccache libffi-dev libssl-dev             libsqlite3-dev libjpeg-dev libpng-dev zlib1g-dev openjdk-11-jdk unzip python3-dev             libsndfile1 libopenblas-dev

      - name: Install buildozer and heavy deps (may take long)
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36
          pip install torch==1.13.1+cpu torchvision==0.14.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install easyocr pillow

      - name: Build (debug)
        run: buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
